<?php
/*
 * Plugin Name: Municipios de Nicaragua Woocommerce
 * Plugin URI: https://mokacreativa.com/
 * Description: Muestra los municipios de Nicaragua en Woocommerce
 * Author: Frander Mejía
 * Author URI: https://mokacreativa.com/
 * Version: 1.0.0
 */

add_filter( 'woocommerce_states', 'techiepress_custom_shipping_zones' );

function techiepress_custom_shipping_zones( $states ) {
   
    $states['NI'] = array(
        'NI001' => 'Nagarote',    
        'NI002' => 'Chichigalpa',    
        'NI003' => 'Chinandega',
   'NI004' => 'La Paz Centro',
        'NI005' => 'Leon',    
        'NI006' => 'Nandaime',    
        'NI007' => 'Catarina',
        'NI008' => 'Dolores ',        
        'NI009' => 'Jinotepe',    
        'NI0010' => 'Masatepe',    
        'NI0011' => 'Masaya',
        'NI0012' => 'Nindiri',        
        'NI0013' => 'Niquinohomo',    
        'NI0014' => 'Santa Teresa',    
        'NI0015' => 'San Marcos',
        'NI0016' => 'Diriamba ',        
        'NI0017' => 'La Paz Carazo',    
        'NI0018' => 'Rivas ',    
        'NI0019' => 'Ochomogo',
        'NI0020' => 'Belen ',
        'NI0021' => 'Granada',    
        'NI0022' => 'Diriomo',    
        'NI0023' => 'La Concepcion',
        'NI0024' => 'Juigalpa ',
        'NI0025' => 'Teustepe',    
        'NI0026' => 'Boaco',    
        'NI0027' => 'Camoapa',
        'NI0028' => 'Tecolostote ',        
        'NI0029' => 'San Lorenzo',    
        'NI0030' => 'San Benito',    
        'NI0031' => 'Las Banderas',
        'NI0032' => 'Matagalpa ',        
        'NI0033' => 'Ciudad Dario',    
        'NI0034' => 'Sebaco',    
        'NI0035' => 'Jinotega',
        'NI0036' => 'Las Maderas ',        
        'NI0037' => 'Condega',    
        'NI0038' => 'Esteli',    
        'NI0039' => 'Ocotal',
        'NI0040' => 'Palacaguina',
        'NI0041' => 'Somoto',    
        'NI0042' => 'Managua',    
        'NI0043' => 'Ticuantepe',
        'NI0044' => 'Ciudad Sandino',
        'NI0045' => 'Los Brasiles',    
        'NI0046' => 'Mateare ',    
        'NI0047' => 'Tipitapa',
        'NI0048' => 'Nejapa ',        
        'NI0049' => 'Veracruz',    
        'NI0050' => 'Telica',    
        'NI0051' => 'El Viejo',
        'NI0052' => 'Corinto ',        
        'NI0053' => 'Posoltega',    
        'NI0054' => 'Quezalquaque',    
        'NI0055' => 'Nandasmo',
        'NI0056' => 'San Juan de Oriente ',        
        'NI0057' => 'Tisma',    
        'NI0058' => 'San Jorge',    
        'NI0059' => 'Potosi',
        'NI0060' => 'Diriamba ',
        'NI0061' => 'La Conquista',    
        'NI0062' => 'Buenos Aires',    
        'NI0063' => 'Popuyuapa',
        'NI0064' => 'Santo Tomas ',
        'NI0065' => 'Acoyapa',    
        'NI0066' => 'La Trinidad',    
        'NI0067' => 'San Isidro',
        'NI0068' => 'Pueblo Nuevo ',        
        'NI0069' => 'Totogalpa',    
        'NI0070' => 'Yalaguina',    
        'NI0071' => 'El Cruzero',
        'NI0072' => 'Somotillo ',        
        'NI0073' => 'Villa Nueva',    
        'NI0074' => 'El Sauce',    
        'NI0075' => 'Mina el Limon',
        'NI0076' => 'Malpaisillo ',        
        'NI0077' => 'San Jacinto',    
        'NI0078' => 'El Realejo',    
        'NI0079' => 'Tola',
        'NI0080' => 'Montelimar ',
        'NI0081' => 'San Rafael del Sur',    
        'NI0082' => 'Villa el Carmen',    
        'NI0083' => 'Masachapa',
        'NI0084' => 'San Juan del Sur ',
        'NI0085' => 'Pochomil',    
        'NI0086' => 'Cara de Mono',    
        'NI0087' => 'La Gateada',
        'NI0088' => 'Muelle de Bueyes ',        
        'NI0089' => 'El Cacao',    
        'NI0090' => 'Nueva Guinea',    
        'NI0091' => 'Comalapa'  ,
        'NI0092' => 'Colonia Rama ',        
        'NI0093' => 'Muy Muy',    
        'NI0094' => 'Matiguas',    
        'NI0095' => 'Santo Domingo',
        'NI0096' => 'Villa Sandino ',        
        'NI0097' => 'La Batea',    
        'NI0098' => 'El Rama',    
        'NI0099' => 'Muhan',
        'NI0100' => 'El Coral ',
        'NI0101' => 'Puerto La Esperanza',    
        'NI0102' => 'La Libertad',    
        'NI0103' => 'San Ramon',
        'NI0104' => 'San Rafael del Norte ',
        'NI0105' => 'La Concordia',    
        'NI0106' => 'La Dalia',    
        'NI0107' => 'El Tuma',
        'NI0108' => 'Momotombo ',        
        'NI0109' => 'Tonala',    
        'NI0110' => 'El Jicaral',    
        'NI0111' => 'La Reynaga',
        'NI0112' => 'Rancheria ',        
        'NI0113' => 'Cinco Pinos',    
        'NI0114' => 'Moyogalpa',    
        'NI0115' => 'Altagracia',
        'NI0116' => 'La Virgen ',        
        'NI0117' => 'La Boquita',    
        'NI0118' => 'San Jose de I.Remates',    
        'NI0119' => 'El Tule',
        'NI0120' => 'La Esperanza ',
        'NI0121' => 'San Miguelito',    
        'NI0122' => 'Los Chiles',    
        'NI0123' => 'Talolinga',
        'NI0124' => 'El Almendro ',
        'NI0125' => 'San Carlos',    
        'NI0126' => 'Santa Lucia',    
        'NI0127' => 'Mulukuku',
        'NI0128' => 'Paiwas ',        
        'NI0129' => 'El Triunfo',    
        'NI0130' => 'Las Azucenas',    
        'NI0131' => 'Wapi',
        'NI0132' => 'Cuapa ',        
        'NI0134' => 'Rio Blanco',    
        'NI0135' => 'El Ayote',    
        'NI0136' => 'Terranova',
        'NI0137' => 'Naranjo ',        
        'NI0138' => 'Waslala',    
        'NI0139' => 'Pantasma',    
        'NI0140' => 'Rancho Grande',
        'NI0141' => 'Laurel Galan ',
        'NI0142' => 'San Fco. Libre',    
        'NI0143' => 'Puerto Viejo',    
        'NI0144' => 'El Guineo',
        'NI0145' => 'Cardenas ',
        'NI0146' => 'Santa Rosa del Peñonn',    
        'NI0147' => 'Guasaule',    
        'NI0148' => 'Puerto Morazan',
        'NI0149' => 'Peñas Blancas ',        
        'NI0150' => 'Las Manos',    
        'NI0151' => 'Santo Tomas del Norte',    
        'NI0152' => 'Dipilto',
        'NI0153' => 'Plan de Grama ',        
        'NI0154' => 'Puerto Sandino',    
        'NI0155' => 'Achuapa',    
        'NI0156' => 'Las Salinas',
        'NI0157' => 'Malacatoya ',        
        'NI0158' => 'Rancho S. Ana',    
        'NI0159' => 'Boca de Sabalos',    
        'NI0160' => 'Sapoa',
        'NI0161' => 'Ayapal',          
        'NI0162' => 'Santa Rita',
        'NI0163' => 'La Rica',        
        'NI0164'  => 'Ciudad Antigua',    
        'NI0165' => 'Poneloya',    
        'NI0166' => 'Las Peñitas',
        'NI0167'  => 'Corn Island',
    );
   
    return $states ;
}